default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: app-mail-vuejs_development
test:
  <<: *default
  database: app-mail-vuejs_test

production:
  <<: *default
  database: app-mail-vuejs_production
  username: app-mail-vuejs
  password: <%= ENV['APP-MAIL-VUEJS_DATABASE_PASSWORD'] %>
